# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6c69d891e109e34f2144f90ab186950c8331fe327049384565136e5ff66b00e6955d07512aa09953c89bbf2c5b704f90dda2b9821e0deb3024bd69dec6f3329d

test:
  secret_key_base: 920c2396df1be3e5749432daeb9cda50e1c1d7de0027c82d140fb7b3434c9671b75022cc26190fd1c66ff50bff9be643f2304bcdc7f49e07f35c29fdbe277cd0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
